### ISSUE TITLE
Ad "Skipping files with existing tags" option

### ISSUE THREAD

**Issue by DamienZaid** [pjmeca/volume-normalizer#3]
Using rsgain easy you can specify "-S" to skip files with existing tags. This would be a good option to not process all previously processed files, until you implement some kind of database to store previously processed files.

**Comment by DamienZaid** [comment]
Another possibility could be to add the rsgain command to the compose file, so people could specify their own settings.

For example:
`command: easy -m MAX -p user_preset -S`

**Comment by pjmeca** [comment]
Both options can be easily implemented, but I'm not sure if we should proceed that way. I conceived this project as an abstraction over rsgain to keep it simple; therefore, I don't want to replicate every option rsgain offers as environment variables in the compose file.

However, to avoid limiting options, I will follow your second suggestion and provide an environment variable where the user can input their own configurations. But, as I mentioned, my intention is not to replicate all the behavior of rsgain in the docker-compose.

**Comment by DamienZaid** [comment]
Hey pjmeca,

it seems like the ADDITIONAL_ARGS are not applied.
I tried `-S` and `--skip-existing` but both variants just rescan every file

**Comment by pjmeca** [comment]
Hmmm, you are right. It seems that the value of `ADDITIONAL_ARGS` is lost between the calls of both shell scripts:

```sh
volume-normalizer  | ADDITIONAL_ARGS: -S
volume-normalizer  | Cron configured to run with * * * * *: Every minute
volume-normalizer  | Starting rsgain...                                                                                                         
volume-normalizer  | ADDITIONAL_ARGS: 
volume-normalizer  | /usr/bin/rsgain easy -m MAX -p no_album /mnt
```

This is strange because I specifically tried with the `-S` option the other day and it worked. I will take a look at this ASAP.

**Comment by pjmeca** [comment]
Hey @DamienZaid, I just uploaded a fix under tag v1.3.2. Could you please confirm if it's now working properly?

**Comment by DamienZaid** [comment]
I just tested it and it seems like it still scans all files again.

This is the output from volume-normalizer (the files already had replay gain tags)
```
volume-normalizer  | Starting rsgain...
volume-normalizer  | [✔] Applying preset 'user_preset'...
volume-normalizer  | [✔] Building directory tree...
volume-normalizer  | [✔] Found 8 directories...
volume-normalizer  | [✔] Scanning directories for files...
volume-normalizer  | [✔] Scanning with 5 threads...

volume-normalizer  | Scanning Complete
volume-normalizer  | Time Elapsed:      00:00:13
volume-normalizer  | Files Scanned:     68
volume-normalizer  | Clip Adjustments:  0 (0.0% of files)
volume-normalizer  | Average Gain:      -2.92 dB
volume-normalizer  | Average Peak:      1.000000 (0.00 dB)
volume-normalizer  | Negative Gains:    68 (100.0% of files)
volume-normalizer  | Positive Gains:    0 (0.0% of files)
volume-normalizer  | 
volume-normalizer  | Job finished.
volume-normalizer  | Sleeping until next run.
```

Here is the output if I use rsgain in shell
```
[✔] Applying preset '/preset/12'...
[✔] Building directory tree...
[✔] Found 8 directories...
[✔] Scanning directories for files...
[✔] Scanning with 5 threads...

Skipped 68 files with existing ReplayGain information
No files were scanned
```

**Comment by DamienZaid** [comment]
Now it works!
```
volume-normalizer  | Starting rsgain...
volume-normalizer  | [✔] Applying preset 'user_preset'...
volume-normalizer  | [✔] Building directory tree...
volume-normalizer  | [✔] Found 8 directories...
volume-normalizer  | [✔] Scanning directories for files...
volume-normalizer  | [✔] Scanning with 5 threads...

volume-normalizer  | Skipped 68 files with existing ReplayGain information
volume-normalizer  | No files were scanned
volume-normalizer  | Job finished.
volume-normalizer  | Sleeping until next run.
```

Thank you very much for implementing ADDITIONAL_ARGS!

**Comment by pjmeca** [comment]
Glad to hear!
